qiniu:
  ak: "tGVRrRRU95FqdcQDQN8s_6PwfMx89xjoGqRhORLC"
  sk: "KYeKFt3Xak8cyUXk4XQMnsXB_6HANR4vlCerjcjA"
  url: "http://timage.wiisong.com"
  bucket: "wiisongtest"
app:
  ssoUrl: "http://www.sso.com"
  saasUrl: "http://www.ws.com"
  jwtSecret: "1dnkjwandawn"
wechat:
  official:
    chatTmpl: "TZMlem2YPA_J7XP9Mvok-xMSYq589YWwzIvzDYpNOZ0"
server:
  address: ":8080"
  serverRoot: ""
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
database:
  logger:
    path: "./storage/sql"
    level: "all"
    stdout: true
  default:
    type: "mysql"
    link: "zjw:zjw123456@tcp(47.115.162.231:3306)/saas_dev?loc=Local&parseTime=true"
    debug: true
redis:
  # 单实例配置示例1
  default:
    address: 127.0.0.1:6379
    pass:
    db: 5
