logger:
  path: "D:\\code\\kfbackend\\storage\\log\\"
  file: "{Y-m-d}.log"
  ws:
    path: "D:\\code\\kfbackend\\storage\\log\\ws"
    level: "debug"
storage:
  default: 'local'
  qiniu:
    ak: ""
    sk: ""
    url: ""
    bucket: ""
app:
  jwtSecret: ""
  host: "127.0.0.1:8080"
server:
  address: ""
  serverRoot: ""
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
database:
  logger:
    path: "./storage/log/db"
    level: "all"
    stdout: true
  default:
    type: "mysql"
    link: "root:123456@tcp(127.0.0.1:3306)/dev?loc=Local&parseTime=true"
    debug: true
    charset: "utf8mb4"
redis:
  # 单实例配置示例1
  default:
    address: 127.0.0.1:6379
    pass:
    db: 5