# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
database:
  default:
    type: "mysql"
    link: "root:123456@tcp(127.0.0.1:3306)/dev?loc=Local&parseTime=true"
gfcli:
  gen:
    dao:
    - link: "mysql:root:123456@tcp(127.0.0.1:3306)/dev?loc=Local&parseTime=true"
      jsonCase: "SnakeScreaming"


